- link:
    ~/.zsh: tochka/zsh
    ~/.oh-my-zsh: tochka/oh-my-zsh
    ~/.zprofile: tochka/zprofile
    ~/.zshrc: tochka/zshrc

- shell:
    - [brew install zsh fzf, Installing zsh and fzf]
    - [sudo scripts/add-shell $(which zsh), Adding zsh to list of allowed shells]
    - [chsh -s $(which zsh), Changing default shell to zsh]
