source ~/.zsh/antigen.zsh

antigen use oh-my-zsh

antigen bundle ssh-agent
antigen theme random

antigen apply

export PATH=/usr/local/bin:$PATH

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Modify zsh completion system to make lowercase letters match lowercase and
# uppercase letters.
# https://superuser.com/a/1092328
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
autoload -Uz compinit && compinit
