export PATH=$HOME/bin:/usr/local/bin:/opt/homebrew/bin:$HOME/.composer/vendor/bin:$PATH
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="sui"
DISABLE_AUTO_UPDATE="true"
DISABLE_AUTO_TITLE="true"
ZSH_CUSTOM=$HOME/.zsh

plugins=(ssh-agent)

source $ZSH/oh-my-zsh.sh

# User configuration

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias zshr="source ~/.zshrc"
alias ssh="TERM=xterm ssh"
