#!/usr/bin/env bash

set -e

CONFIG=$1
CONFIG_DIR="configs"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive

if [[ -z $CONFIG ]]; then
  echo "Please specify a config."
  exit 1
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_DIR}/${CONFIG}.yaml"
