- clean: ['~']

- defaults:
    shell:
      stdout: true
      stderr: true

- link:
    ~/.config/nvim:
      create: true
      path: tochka/config/nvim
    ~/:
      glob: true
      path: tochka/*
      prefix: '.'
      exclude: [ tochka/config ]
